apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.initConfigName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  svc-user.js: |
    const dbname = 'flam';
    const rootUsername = process.env['MONGO_INITDB_ROOT_USERNAME']
    const rootPassword = process.env['MONGO_INITDB_ROOT_PASSWORD']
    const svcUsername = process.env['MONGO_INITDB_SVC_USERNAME']
    const svcPassword = process.env['MONGO_INITDB_SVC_PASSWORD']

    db = db.getSiblingDB('admin');
    db.auth(rootUsername, rootPassword);
    db.createUser({
      user: svcUsername,
      pwd: svcPassword,
      roles: [{ role: 'readWrite', db: dbname }],
    });

    db = db.getSiblingDB(dbname);
    db.createCollection('comments');
    db.createCollection('submissions');
