{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
data:
  username: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
