{{- if .Values.secrets.root.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretNameRoot" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
data:
  username: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}

{{- if .Values.secrets.svc.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.secretNameSvc" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
data:
  username: {{ randAlphaNum 32 | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
