apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "submission-service.fullname" . }}
  labels:
    {{- include "submission-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "submission-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "submission-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "submission-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              path: /api/health
              port: http
          readinessProbe:
            tcpSocket:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "submission-service.mongo-secret" . }}
                  key: {{ .Values.mongo.secret.usernameKey }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "submission-service.mongo-secret" . }}
                  key: {{ .Values.mongo.secret.passwordKey }}
            - name: MONGO_SERVER
              value: {{ include "submission-service.mongo-server" . }}
            - name: MONGO_PORT
              value: "{{ .Values.mongo.port }}"
            - name: FlamFlamDb__ConnectionString
              value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_SERVER):$(MONGO_PORT)
            - name: FlamFlamDb__DatabaseName
              value: flam
            - name: FlamFlamDb__SubmissionsCollectionName
              value: submissions
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
