apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatcher-service.fullname" . }}
  labels:
    {{- include "dispatcher-service.labels" . | nindent 4 }}
data:
  config.json: |
    {
        "debug": false,
        "comment_endpoint": "http://comment-service:8080",
        "submission_endpoint": "http://submission-service:8080",
        "subreddits": [
            "all"
        ]
    }
