apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatcher-service.fullname" . }}
  labels:
    {{- include "dispatcher-service.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "debug": "{{ .Values.config.debug }}",
      "comment_endpoint": "{{ include "dispatcher-service.comment-endpoint" . }}",
      "submission_endpoint": "{{ include "dispatcher-service.submission-endpoint" . }}",
      "subreddits": {{ .Values.config.subreddits | toJson }}
    }
