apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatcher-service.fullname" . }}
  labels:
    {{- include "dispatcher-service.labels" . | nindent 4 }}
data:
  config.json: >-
    {{ .Values.config | toJson }}
