apiVersion: v2
name: dispatcher-service
description: A Helm chart for flam-flam/dispatcher-service
type: application
version: 0.1.1
appVersion: "0.6.0"

home: https://flam-flam.github.io
sources:
  - https://github.com/flam-flam/dispatcher-service
  - https://github.com/flam-flam/helm-charts/tree/main/charts/dispatcher-service
